- name: module docker_image
  hosts: node1
  become: yes
  tasks:
  - name: install docker & docker for python
    apt: 
      name: docker.io,python3-docker
      state: present
      update_cache: yes
      cache_valid_time: 3600
  - name: start docker
    systemd:
      name: docker
      state: started
      enabled: yes

  - name: run
    docker_container:
      name: "n{{ item }}"
      image: nginx:latest
      state: started
    with_sequence: count=3
  
  - name: container list
    docker_host_info:
      containers: True
    register: __docker_info

  - name: collecte ips
    docker_container_info:
      name: '{{ item.Names[0] |regex_replace("^/", "") }}'
    register: container_infos
    loop: '{{ __docker_info.containers }}'
  
  - name: print
    debug:
      msg: "{{ item.container.NetworkSettings.Networks.bridge.IPAddress }}"
    with_items:
    - "{{ container_infos.results }}"

  - name: infos about network
    docker_network_info:
      name: maxime
    register: __network_infos
  - name: debug
    debug:
      var: __network_infos

  - name: Create directory
    file:
      path: /tmp/data
      state: directory
  - name: Create volume
    docker_volume:
      name: maxime_data
      driver: local
      driver_options:
        o: bind
        type: none
        device: /tmp/data
  - name: get info about volume
    docker_volume_info:
      name: maxime_data
    register: __volume_infos
  - name: print
    debug:
      var: __volume_infos
