---
# handlers file for roles/mariadb
- name: restart_mariadb
  service:
    name: mariadb
    state: restarted

- name: reload_mariadb
  service:
    name: mariadb
    state: reloaded

- name: reconfigure_data_dir
  become: true
  become_user: mysql
  shell:
    cmd: |
      systemctl stop mariadb
      mv /var/lib/mysql/* {{ mariadb_data_dir }}
      systemctl start mariadb
  ignore_errors: true
  notify: restart_mariadb
