- name: concatener des fichiers
  hosts: node1
  tasks: 
  - name: dir
    file:
      path: /tmp/sources
      state: directory
  - name: copy 
    copy: 
      src: "{{ item }}"
      dest: /tmp/sources/
    with_items:
    - t1
    - t2
    - t3
  - name: test assemble
    assemble:
      src: /tmp/sources
      dest: /tmp/myconf.cfg
      delimiter: |
        ## delimiter
        ## fichier

