ec2_provision_access_key: "{{ vault_ec2_access_key }}"
ec2_provision_secret_key: "{{ vault_ec2_secret_key }}"

ec2_provision_key_name: my_ssh_key
ec2_provision_region: us-east-1
image: ami-04a81a99f5ec58529
id_wordpress: wp_wordpress
id_mariadb: wp_mariadb

sec_group_wordpress: ssh-sg-wordpress
sec_group_mariadb: ssh-sg-mariadb

vpc_id: vpc-0425e8508106ec64c

mysql_db: "wordpress"
mysql_user: "maxime"
mysql_password: "password"



