---
# tasks file for roles/mariadb
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: install MariaDB
  ansible.builtin.apt:
    name: 
    - "mariadb-server-{{ mariadb_version }}"
    - "mariadb-client-{{ mariadb_version }}"
    - software-properties-common
    state: present
    update_cache: true

- name: create directory for MariaDB data
  file:
    path: "{{ mariadb_data_dir }}"
    state: directory
    mode: 0750
    owner: mysql
    group: mysql
  when: mariadb_data_dir != ""

- name: "mariadb.conf change listen address"
  lineinfile:
    path: "/etc/mysql/mariadb.conf.d/50-server.cnf"
    regexp: "^bind-address"
    line: "bind-address = {{ mariadb_listen_address }}"
    state: present
  notify: restart_mariadb

- name: "mariadb.conf change data directory"
  lineinfile:
    path: "/etc/mysql/mariadb.conf.d/50-server.cnf"
    regexp: "^datadir"
    line: "datadir = {{ mariadb_data_dir }}"
    state: present
  when: mariadb_data_dir != ""
  notify: reconfigure_data_dir

- name: "change mariadb.conf to include custom file"
  lineinfile:
    path: "/etc/mysql/mariadb.conf.d/50-server.cnf"
    insertafter: "[mysqld]"
    line: "!includedir /etc/mysql/mariadb.custom.d/"
    state: present
  notify: restart_mariadb

- name: Ensure custom configuration directory exists
  ansible.builtin.file:
    path: /etc/mysql/mariadb.custom.d
    state: directory
    mode: '0750'
    owner: mysql
    group: mysql
    
- name: "add custom Mariadb configuration file"
  template:
    src: mariadb.custom.cnf.j2
    dest: /etc/mysql/mariadb.custom.d/mariadb.custom.cnf
    mode: 0640
    owner: mysql
    group: mysql
  notify: restart_mariadb

- name: add my.cnf
  template:
    src: my.cnf.j2
    dest: "/etc/mysql/my.cnf"
    mode: 0640
    owner: mysql
    group: mysql
  notify: reload_mariadb

- meta: flush_handlers
- name: start MariaDB
  service:
    name: mariadb
    state: started
    enabled: true

