- name: module docker_image
  hosts: all
  become: yes
  vars_files:
    - /home/maxime/secrets.yml
  tasks:
  - name: install docker & docker for python
    apt: 
      name: docker.io,python3-docker
      state: present
      update_cache: yes
      cache_valid_time: 3600
  - name: start docker
    systemd:
      name: docker
      state: started
      enabled: yes
  
  - name: docker login
    docker_login:
      registry_url: registry.gitlab.com
      username: maxime.meuley77
      password: "{{ token_gitlab }}"

  - name: build
    docker_image:
      name: registry.gitlab.com/maxime.meuley77/cours-container/imgbuild
      tag: v1.1
      source: build
      push: yes
      build: 
        path: /tmp/
        dockerfile: Dockerfile
        cache_from:
          - ubuntu:24.04
